/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    SITE_NAME: 'Next Blog',
    SITE_DESCRIPTION: 'Generated by create next app and used Ninja technique.',
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.amazonaws.com',
        pathname: '/secure.notion-static.com/**',
      },
    ],
  },
};

module.exports = nextConfig;
