import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';
import { PropsWithChildren } from 'react';
import './globals.tailwind.css';

export const metadata = {
  title: 'Next Blog',
  description: 'Generated by create next app',
};

type Props = PropsWithChildren;

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className="bg-black font-sans leading-normal tracking-normal">
        {/* Header */}
        <Header title={metadata.title} />

        {/* Content */}
        {children}

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
